name = "zk-detective-server"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "GAME_SERVER", class_name = "GameServerDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameServerDO"]
